### ISSUE TITLE
[Feature Request] Non exe available to select

### ISSUE THREAD

**Issue by ghyujkilop** [astrogab42/XwbAudioReplacer#16]
Hi,

Problem is I'm trying to use this to repack an xwb for an xiso file for Xemu. But there's no exe that's unpacked from an xiso file. Can we bypass this exe selection? Or is it required?

Again, xiso's don't come with exes. I tried selecting the default.xbe file but it says it requires an exe.

**Comment by astrogab42** [comment]
Hi @ghyujkilop , if you are referring to the "Set the path to the exe file of the game launcher" option in the configuration phase of XWB-Repacker, this is NOT a mandatory field and it can be easily set to False. Simply, the script will not run the game after the repacking is complete.
Please, let us know if this solves your problem. Thanks!
